export const GET_MEMBERS_LIST = 'GET_MEMBERS_LIST';
export const GET_MEMBERS_LIST_SUCCESS = 'GET_MEMBERS_LIST_SUCCEESS';
export const GET_MEMBERS_LIST_ERROR = 'GET_MEMBERS_LIST_ERROR';

export const GET_MEMBER = 'GET_MEMBER';
export const GET_MEMBER_SUCCESS = 'GET_MEMBER_SUCCESS';
export const GET_MEMBER_ERROR = 'GET_MEMBER_ERROR';