export const GET_TRANSACTIONS_LIST = 'GET_TRANSACTIONS_LIST';
export const GET_TRANSACTIONS_LIST_SUCCESS = 'GET_TRANSACTIONS_LIST_SUCCESS';
export const GET_TRANSACTIONS_LIST_ERROR = 'GET_TRANSACTIONS_LIST_ERROR';